char *infinite_add(char *n1, char *n2, char *r, int size_r);
char *rot13(char *);
void print_number(int n);
char *leet(char *);
char *cap_string(char *);
int _putchar(char c);
char *string_toupper(char *);
void reverse_array(int *a, int n);
int _strcmp(char *s1, char *s2);
char *_strncpy(char *dest, char *src, int n);
char *_strncat(char *dest, char *src, int n);
char *_strcat(char *dest, char *src);
